### PR TITLE
Updated LICENSE.

### LINKED ISSUE #7: Change license
... to match curriculum et al

### PR DESCRIPTION
**Pull request by mookerji**
Closes #7.

r=@bridgethillyer

### CODE REVIEW

**Comment by seancorfield** [comment]
:+1:

**Comment by davidchambers** [comment]
:+1:

**Comment by mookerji** [comment]
Ack, I missed the license update in the `project.clj`. Updated.

**Comment by davidchambers** [comment]
It would be nice to squash these commits. ;)

**Comment by mookerji** [comment]
Done! Thanks, guys.

**Comment by mookerji** [comment]
Hey, can we merge this? @seancorfield @davidchambers Thanks!

**Comment by bridgethillyer** [comment]
Hmmmm... we have conflicts on this one.

**Comment by davidchambers** [comment]
Could you resolve the merge conflicts, @mookerji?

**Comment by yokolet** [comment]
Since this PR is going older and older, I fixed conflict and merged.
Our quil app license has been updated to Creative Commons.

**Comment by mookerji** [comment]
Ack, sorry about that. Thanks @yokolet .

**Pull request merged**
